namespace Polaris.API
{
    /// <summary>
    /// 每一种可订阅的游戏内回调。显式赋值，只允许在末尾追加：这些值会被诊断页、能力报告和
    /// （未来）内容定义引用，改名或复用数值会让旧记录错位。
    /// <para>
    /// 按 <c>docs</c> 里的实施计划分批落地；已经出现在这里但暂时没有对应 <see cref="GameSignal{T}"/>
    /// 挂上去的值，<see cref="CallbackRegistry.Status"/> 一律回答 <see cref="GameCallbackAvailability.Unsupported"/>。
    /// </para>
    /// </summary>
    public enum GameCallbackKind
    {
        // ── 7.1 生命周期与存读档 ──────────────────────────────────────────────
        Ready = 0,
        UnitySceneLoaded = 1,
        UnitySceneUnloaded = 2,
        ActiveSceneChanged = 3,
        GameSceneStarting = 4,
        GameSceneStarted = 5,
        NewGameStarting = 6,
        NewGameStarted = 7,
        SaveLoading = 8,
        SaveLoaded = 9,
        SaveFailed = 10,
        SaveSerializing = 11,
        SaveSerialized = 12,
        SaveWriting = 13,
        SaveWritten = 14,
        AutoSaveStarting = 15,
        AutoSaveCompleted = 16,
        GameRestarting = 17,
        GameRestarted = 18,
        GameOverStarted = 19,
        GameOverEnded = 20,
        LocaleChanged = 21,
        FocusChanged = 22,
        ApplicationPauseChanged = 23,
        Stopping = 24,

        // ── 7.2 循环、输入和时间 ──────────────────────────────────────────────
        Updating = 25,
        LateUpdating = 26,
        FixedUpdating = 27,
        GameFrameAdvanced = 28,
        ActionPressed = 29,
        ActionReleased = 30,
        FocusInputSuppressed = 31,

        // ── 7.3 世界、地图和事件系统 ──────────────────────────────────────────
        WorldEntered = 32,
        WorldExited = 33,
        MapChanging = 34,
        MapChanged = 35,
        MapOpened = 36,
        MapClosed = 37,
        MapActionInitialized = 38,
        MapActionClosed = 39,
        TransferStarting = 40,
        TransferCompleted = 41,
        SafeAreaChanged = 42,
        GameMenuAvailabilityChanged = 43,
        DayNightChanged = 44,
        NightLevelChanged = 45,
        DangerLevelChanged = 46,
        DangerBonusChanged = 47,
        WeatherChanged = 48,
        RainLevelChanged = 49,
        EventOpened = 50,
        EventClosed = 51,
        TalkTargetChanged = 52,
        SummonerOpened = 53,
        SummonerClosed = 54,

        // ── 7.4 角色、玩家和状态 ──────────────────────────────────────────────
        PlayerAvailable = 55,
        PlayerUnavailable = 56,
        CharacterSpawned = 57,
        CharacterDespawned = 58,
        PlayerStateChanging = 59,
        PlayerStateChanged = 60,
        EnemyStateChanged = 61,
        PlayerPoseChanged = 62,
        PlayerJumped = 63,
        PlayerLanded = 64,
        CharacterTeleported = 65,
        CharacterHpChanged = 66,
        CharacterMpChanged = 67,
        PlayerDeathStarting = 68,
        PlayerDied = 69,
        PlayerRevived = 70,
        EnemyDied = 71,
        KnockbackApplied = 72,
        StatusAdded = 73,
        StatusRefreshed = 74,
        StatusRemoved = 75,

        // ── 7.5 战斗、伤害和恢复 ──────────────────────────────────────────────
        AttackPublished = 76,
        DamageApplying = 77,
        DamageApplied = 78,
        HpDamageApplied = 79,
        MpDamageApplied = 80,
        MapDamageApplied = 81,
        SlipDamageApplied = 82,
        GasDamageApplied = 83,
        PressDamageApplied = 84,
        AbsorbDamageApplied = 85,
        RecoveryApplied = 86,
        KillPublished = 87,
        BattleStarted = 88,
        EnemySummoned = 89,
        BattleEnded = 90,
        EnemyOverdriveStarted = 91,
        EnemyOverdriveEnded = 92,

        // ── 7.6 魔法和玩家动作 ────────────────────────────────────────────────
        MagicCreated = 93,
        ChantStarted = 94,
        ChantCompleted = 95,
        ChantCancelled = 96,
        MagicCast = 97,
        MagicExploded = 98,
        MagicClosed = 99,
        PlayerActionRejected = 100,

        // ── 7.7 背包、掉落、物品使用和经济 ───────────────────────────────────
        ItemAdded = 101,
        ItemRemoved = 102,
        ItemsTransferred = 103,
        StorageCleared = 104,
        ItemObtained = 105,
        ItemUseStarting = 106,
        ItemUsed = 107,
        DropCreated = 108,
        DropPickedUp = 109,
        DropRemoved = 110,
        CoinPickedUp = 111,
        MoneyChanged = 112,
        ItemBought = 113,
        ItemSold = 114,

        // ── 7.8 制作、配方和工作台（与 UI.CraftingOpened/Closed 共享同一个 Signal） ─
        CraftingOpened = 115,
        CraftingClosed = 116,
        CraftingStarted = 117,
        CraftingCompleted = 118,
        CraftingFailed = 119,
        RecipeSelected = 120,

        // ── 7.9 任务、剧情和成长 ──────────────────────────────────────────────
        QuestStarted = 121,
        QuestUpdated = 122,
        QuestCompleted = 123,
        QuestRemoved = 124,
        FocusedQuestChanged = 125,
        QuestCollectionChanged = 126,
        QuestSummonerChanged = 127,
        StoryFlagChanged = 128,
        AchievementChanged = 129,
        SkillUnlocked = 130,
        MagicUnlocked = 131,
        EnemyDefeatRecorded = 132,

        // ── 7.10 游戏内 UI、菜单、对话和工作台 ───────────────────────────────
        GameMenuOpening = 133,
        GameMenuOpened = 134,
        GameMenuClosing = 135,
        GameMenuClosed = 136,
        GameMenuStateChanged = 137,
        GameMenuCategoryChanged = 138,
        BenchMenuOpened = 139,
        BenchMenuClosed = 140,
        SaveMenuOpened = 141,
        SaveMenuClosed = 142,
        DialogueOpened = 143,
        DialogueClosed = 144,
        InteractionTargetChanged = 145,

        // ── 7.11 音频 ────────────────────────────────────────────────────────
        MusicChanged = 146,
        MusicPlaybackChanged = 147,
        PolarisPlaybackChanged = 148,
        SoundPlayed = 149,
        VolumeChanged = 150,
    }
}
