using System.Text;

namespace Polaris.Event.Compiler.Emission
{
    /// <summary>
    /// 生成一个自注册的 registrar 类 + <c>GeneratedEvents</c> 的一个 partial 声明。多个 .phxx 文件各自
    /// 贡献 <c>GeneratedEvents</c> 的一个 partial class 声明、各自一个静态属性，天然不会冲突。
    /// </summary>
    public static class CSharpEmitter
    {
        public static string Emit(string eventNamespace, string rootNamespace, string logicalId, string sourcePath, string commandText, string contentHash)
        {
            string safeName = MakeSafeIdentifier(logicalId);
            // 事件命名空间（运行时字符串，如 "com.example.mymod"）和生成代码所在的 C# 命名空间是两回事：
            // 前者可以是任意字符串，后者必须是合法标识符链，因此改用宿主项目自己的 RootNamespace 派生
            // csNamespace，不能直接把 eventNamespace 当 C# 命名空间拼——设计文档 §4.3 的示例图省略了
            // 这个区别。两个参数目前调用方（PolarisEventGenerator）传的是同一个值（VS 项目的默认命名
            // 空间），但接口上仍保留独立参数，允许以后重新引入单独配置。
            string csNamespace = string.IsNullOrEmpty(rootNamespace) ? "PolarisEvent.Generated.Events" : $"{rootNamespace}.Generated.Events";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"namespace {csNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [global::Polaris.Event.PolarisEventAutoRegistration({Literal(eventNamespace)})]");
            sb.AppendLine($"    public sealed class {safeName}_Registrar : global::Polaris.Event.IPolarisEventRegistrar");
            sb.AppendLine("    {");
            sb.AppendLine("        public void Register(global::Polaris.Event.PolarisEventRegistrationContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            context.Register(");
            sb.AppendLine($"                logicalId: {Literal(logicalId)},");
            sb.AppendLine($"                commandText: {Literal(commandText)},");
            sb.AppendLine($"                sourcePath: {Literal(sourcePath)},");
            sb.AppendLine($"                contentHash: {Literal(contentHash)});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static partial class GeneratedEvents");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static global::Polaris.Event.PolarisEventReference {safeName} {{ get; }}");
            sb.AppendLine($"            = new global::Polaris.Event.PolarisEventReference({Literal(eventNamespace)}, {Literal(logicalId)});");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static string MakeSafeIdentifier(string logicalId)
        {
            var sb = new StringBuilder();
            foreach (char c in logicalId)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            if (sb.Length == 0 || char.IsDigit(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }

        static string Literal(string value)
        {
            var sb = new StringBuilder();
            sb.Append('"');
            foreach (char c in value ?? string.Empty)
            {
                switch (c)
                {
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        sb.Append(c);
                        break;
                }
            }

            sb.Append('"');
            return sb.ToString();
        }
    }
}
